### ISSUE TITLE
add support for custom MQTT credentials

### ISSUE THREAD

**Issue by mdvickst** [gordlea/fireboard2mqtt#1]
Looks like you can specify MQTT credentials but they are not hooked up to the MQTT client through the options. It would be great to be able to specify MQTT credentials.

**Comment by gordlea** [comment]
I will take a look, thanks for reporting.

**Comment by gordlea** [comment]
Credentials are working for me, can you post your config in yaml format (after scrubbing any passwords, etc)?

If you go to home assistant -> settings -> addons -> fireboard2mqtt -> configuration, then click the 3 dots and pick edit in yaml.

**Comment by mdvickst** [comment]
Sorry for the long delay in getting back to you, my fireboard actually had to go in for repair in the meantime. 

Here is my config:
```
fireboardAccount_email: ########
fireboardAccount_password: #######
mqtt_protocolVersion: "4"
logLevel: debug
verboseLog: true
homeAssistant_prefixEntityNamesWithFireboardId: false
homeAssistant_prefixEntityNamesWithFireboardName: false
mqtt_serverUrl: mqtt://1.2.3.4:1883
mqtt_username: ######
mqtt_password: ######
```

Here is the error I am seeing:
```
[12:13:53] INFO: Preparing to start...
[12:13:54] INFO: Verbose logging enabled.
[fireboard2mqtt:cli] starting fireboard2mqtt
[fireboard2mqtt:cli] initializing mqtt client...
[fireboard2mqtt:cli] mqtt client ready.
[fireboard2mqtt:mqttclient] connecting to mqtt
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/client.js:549:12)
    at work (/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/opt/fireboard2mqtt/.yarn/cache/mqtt-npm-4.3.7-42cab96512-8d4b655d61.zip/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/opt/fireboard2mqtt/.yarn/cache/readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/opt/fireboard2mqtt/.yarn/cache/readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/opt/fireboard2mqtt/.yarn/cache/readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  code: 5
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by gordlea** [comment]
I will add this support to v3. 

I will add the following fields to the config:
* `override_mqtt_url`
* `override_mqtt_username`
* `override_mqtt_password`
